server:
  port: 8222

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5


spring:
  cloud:
    gateway:
      routes:

        # =========================
        # NORMAL ROUTES
        # =========================

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**

        - id: seat-service
          uri: lb://SEAT-SERVICE
          predicates:
            - Path=/api/seats/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**

        # =========================
        # SWAGGER ROUTES
        # =========================

        - id: user-service-openapi
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: event-service-openapi
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event-service/v3/api-docs
          filters:
            - RewritePath=/event-service/(?<path>.*), /$\{path}

        - id: seat-service-openapi
          uri: lb://SEAT-SERVICE
          predicates:
            - Path=/seat-service/v3/api-docs
          filters:
            - RewritePath=/seat-service/(?<path>.*), /$\{path}

        - id: booking-service-openapi
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/v3/api-docs
          filters:
            - RewritePath=/booking-service/(?<path>.*), /$\{path}
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 10
        max-interval: 5000

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

    urls:
      - url: /user-service/v3/api-docs
        name: User Service

      - url: /event-service/v3/api-docs
        name: Event Service

      - url: /seat-service/v3/api-docs
        name: Seat Service

      - url: /booking-service/v3/api-docs
        name: Booking Service

